# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InBound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=128)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutBound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('close', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=512)),
                ('disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('owner', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=512)),
                ('position', models.CharField(max_length=256)),
                ('desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('psd', models.CharField(max_length=128)),
                ('level', models.PositiveSmallIntegerField(default=100)),
                ('disable', models.BooleanField(default=False)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='japi.Product')),
                ('number', models.PositiveIntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='outbound',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japi.Product'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japi.User'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japi.Product'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japi.User'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='outbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japi.OutBound'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japi.Shop'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japi.User'),
        ),
    ]
